application: copper-seeker-734
version: 2015-updated
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /bower_components
  static_dir: bower_components

- url: /data
  static_dir: data

- url: /elements
  static_dir: elements

- url: /images
  static_dir: images

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /
  static_files: index.html
  upload: index.html
